import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

const seedProducts = [
  {
    name: 'Fond de Teint Lumière Invisible',
    slug: 'fond-de-teint-lumiere-invisible',
    price: 42.99,
    originalPrice: 54.99,
    description: 'Un fond de teint léger à couvrance modulable qui unifie le teint tout en laissant respirer la peau. Enrichi en acide hyaluronique pour une hydratation longue durée. Formule sans paraben, testée sous contrôle dermatologique.',
    shortDescription: 'Fond de teint léger à couvrance modulable',
    image: '/images/products/makeup/fond-de-teint.png',
    images: JSON.stringify(['/images/products/makeup/fond-de-teint.png', '/images/products/makeup/fond-de-teint-2.png']),
    category: 'Makeup',
    subcategory: 'Visage',
    rating: 4.7,
    reviewCount: 128,
    inStock: true,
    stockCount: 85,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    tags: JSON.stringify(['fond de teint', 'visage', 'couvrance', 'hyaluronique']),
    sku: 'CG-FDT-001',
  },
  {
    name: 'Rouge à Lèvres Velours Satin',
    slug: 'rouge-a-levres-velours-satin',
    price: 28.50,
    originalPrice: 35.00,
    description: 'Rouge à lèvres longue tenue avec fini satiné velouté. Texture fondante et confortable, riche en pigments pour une couleur intense qui dure toute la journée. Disponible en 12 teintes tendance.',
    shortDescription: 'Rouge à lèvres longue tenue fini satiné',
    image: '/images/products/makeup/rouge-a-levres.png',
    images: JSON.stringify(['/images/products/makeup/rouge-a-levres.png']),
    category: 'Makeup',
    subcategory: 'Lèvres',
    rating: 4.8,
    reviewCount: 256,
    inStock: true,
    stockCount: 120,
    isNew: false,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['rouge à lèvres', 'satin', 'longue tenue']),
    sku: 'CG-RAL-002',
  },
  {
    name: 'Palette Yeux Smoky Glam',
    slug: 'palette-yeux-smoky-glam',
    price: 38.00,
    originalPrice: null,
    description: 'Palette de 12 fards à paupières aux teintes nude et smoky. Formules ultra-pigmentées, faciles à estomper et longue tenue. Inclut un miroir et un double pinceau applicateur. Idéale pour des looks du jour au soir.',
    shortDescription: 'Palette 12 fards nude et smoky ultra-pigmentés',
    image: '/images/products/makeup/palette-yeux.png',
    images: JSON.stringify(['/images/products/makeup/palette-yeux.png', '/images/products/makeup/palette-yeux-2.png']),
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.6,
    reviewCount: 94,
    inStock: true,
    stockCount: 60,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isFeatured: true,
    tags: JSON.stringify(['palette', 'yeux', 'fards', 'smoky', 'nude']),
    sku: 'CG-PYE-003',
  },
  {
    name: 'Mascara Volume Extrême',
    slug: 'mascara-volume-extreme',
    price: 24.99,
    originalPrice: 29.99,
    description: 'Mascara volume et longueur extrême. Sa brosse innovante gainée de fibres capture chaque cil, même les plus fins, pour un regard intense et démesuré. Formule waterproof résistante 24h.',
    shortDescription: 'Mascara volume et longueur waterproof 24h',
    image: '/images/products/makeup/mascara.png',
    images: JSON.stringify(['/images/products/makeup/mascara.png']),
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.5,
    reviewCount: 178,
    inStock: true,
    stockCount: 95,
    isNew: false,
    isTrending: false,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['mascara', 'volume', 'waterproof', 'cils']),
    sku: 'CG-MSC-004',
  },
  {
    name: 'Ensemble Lingerie Dentelle Parisienne',
    slug: 'ensemble-lingerie-dentelle-parisienne',
    price: 65.00,
    originalPrice: 89.00,
    description: 'Ensemble soutien-gorge et culotte en dentelle française fine. Soutien-gorge triangle non rembourré avec armatures légères pour un maintien naturel. Culotte taille haute en dentelle brodée. Tissu doux et respirant.',
    shortDescription: 'Ensemble dentelle française soutien-gorge et culotte',
    image: '/images/products/lingerie/ensemble-dentelle.png',
    images: JSON.stringify(['/images/products/lingerie/ensemble-dentelle.png', '/images/products/lingerie/ensemble-dentelle-2.png']),
    category: 'Lingerie',
    subcategory: 'Ensembles',
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    stockCount: 35,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    tags: JSON.stringify(['lingerie', 'dentelle', 'ensemble', 'soutien-gorge', 'parisienne']),
    sku: 'CG-LIN-005',
  },
  {
    name: 'Nuisette Satin Luxe',
    slug: 'nuisette-satin-luxe',
    price: 49.90,
    originalPrice: null,
    description: 'Nuisette en satin de soie avec détails en dentelle. Coupe fluide et élégante, bretelles ajustables, dos en V avec fermeture éclair invisible. Un classique sensuel revisité avec élégance.',
    shortDescription: 'Nuisette satin de soie avec dentelle',
    image: '/images/products/lingerie/nuisette-satin.png',
    images: JSON.stringify(['/images/products/lingerie/nuisette-satin.png']),
    category: 'Lingerie',
    subcategory: 'Nuisettes',
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    stockCount: 25,
    isNew: false,
    isTrending: false,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['lingerie', 'nuisette', 'satin', 'soie', 'luxe']),
    sku: 'CG-LIN-006',
  },
  {
    name: 'Body Moulant Effet Seconde Peau',
    slug: 'body-moulant-effet-seconde-peau',
    price: 39.50,
    originalPrice: 55.00,
    description: 'Body moulant sans couture en microfibre ultra-douce. Effet seconde peau pour un confort optimal toute la journée. Col en V plongeant, dos nu. Idéal sous une tenue de soirée ou pour un moment de séduction.',
    shortDescription: 'Body moulant sans couture en microfibre',
    image: '/images/products/lingerie/body-moulant.png',
    images: JSON.stringify(['/images/products/lingerie/body-moulant.png']),
    category: 'Lingerie',
    subcategory: 'Bodys',
    rating: 4.4,
    reviewCount: 33,
    inStock: true,
    stockCount: 40,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isFeatured: false,
    tags: JSON.stringify(['lingerie', 'body', 'moulant', 'sans couture']),
    sku: 'CG-LIN-007',
  },
  {
    name: 'Taco Gainer Push-Up',
    slug: 'taco-gainer-push-up',
    price: 22.00,
    originalPrice: null,
    description: 'Taconnes gainer push-up en microfibre avec gel de silicone naturel. Effet galbé naturel et confortable. Bordures invisibles sous les vêtements. Pack de 2 unités.',
    shortDescription: 'Taconnes gainer push-up avec gel silicone',
    image: '/images/products/lingerie/taco-gainer.png',
    images: JSON.stringify(['/images/products/lingerie/taco-gainer.png']),
    category: 'Lingerie',
    subcategory: 'Accessoires',
    rating: 4.3,
    reviewCount: 89,
    inStock: true,
    stockCount: 150,
    isNew: false,
    isTrending: false,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['lingerie', 'taco', 'gainer', 'push-up', 'silicone']),
    sku: 'CG-LIN-008',
  },
  {
    name: 'Bracelet Éclat Doré',
    slug: 'bracelet-eclat-dore',
    price: 18.90,
    originalPrice: 25.00,
    description: 'Bracelet délicat en acier inoxydable doré, orné de strass cristallins. Fermoir magnétique sécurisé. Un accessoire lumineux qui sublimera tous vos looks, du casual à l\'élégant.',
    shortDescription: 'Bracelet acier doré orné de strass cristallins',
    image: '/images/products/accessoires/bracelet-dore.png',
    images: JSON.stringify(['/images/products/accessoires/bracelet-dore.png']),
    category: 'Accessoires',
    subcategory: 'Bijoux',
    rating: 4.6,
    reviewCount: 112,
    inStock: true,
    stockCount: 200,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isFeatured: true,
    tags: JSON.stringify(['bracelet', 'doré', 'strass', 'bijoux', 'acier']),
    sku: 'CG-ACC-009',
  },
  {
    name: 'Trousse Maquillage Voyage',
    slug: 'trousse-maquillage-voyage',
    price: 15.50,
    originalPrice: null,
    description: 'Trousse à maquillage compacte en similicuir noir avec fermeture zip. Compartiments multiples pour organiser vos essentiels beauté. Dimension parfaite pour la trousse de toilette ou le sac à main.',
    shortDescription: 'Trousse maquillage similicuir avec compartiments',
    image: '/images/products/accessoires/trousse-maquillage.png',
    images: JSON.stringify(['/images/products/accessoires/trousse-maquillage.png']),
    category: 'Accessoires',
    subcategory: 'Trousse',
    rating: 4.4,
    reviewCount: 76,
    inStock: true,
    stockCount: 110,
    isNew: false,
    isTrending: false,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['trousse', 'maquillage', 'voyage', 'similicuir', 'noir']),
    sku: 'CG-ACC-010',
  },
  {
    name: 'Pinceau Kabuki Pro',
    slug: 'pinceau-kabuki-pro',
    price: 32.00,
    originalPrice: 40.00,
    description: 'Pinceau kabuki professionnel en fibres synthétiques ultra-douces. Poils denses et souples pour une application uniforme de la poudre, du fond de teint ou du blush. Manche en bambou écologique.',
    shortDescription: 'Pinceau kabuki pro fibres synthétiques',
    image: '/images/products/accessoires/pinceau-kabuki.png',
    images: JSON.stringify(['/images/products/accessoires/pinceau-kabuki.png']),
    category: 'Accessoires',
    subcategory: 'Pinceaux',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    stockCount: 70,
    isNew: false,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    tags: JSON.stringify(['pinceau', 'kabuki', 'professionnel', 'fibres', 'bambou']),
    sku: 'CG-ACC-011',
  },
  {
    name: 'Spray Fixateur Maquillage 24h',
    slug: 'spray-fixateur-maquillage-24h',
    price: 21.90,
    originalPrice: null,
    description: 'Spray fixateur de maquillage longue tenue 24 heures. Brume fine et rafraîchissante qui fixe le maquillage sans dessécher la peau. Enrichi en vitamine E et acide hyaluronique. Sans alcool.',
    shortDescription: 'Spray fixateur longue tenue 24h sans alcool',
    image: '/images/products/makeup/spray-fixateur.png',
    images: JSON.stringify(['/images/products/makeup/spray-fixateur.png']),
    category: 'Makeup',
    subcategory: 'Fixation',
    rating: 4.5,
    reviewCount: 88,
    inStock: true,
    stockCount: 90,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    tags: JSON.stringify(['spray', 'fixateur', 'maquillage', 'longue tenue', 'vitamine E']),
    sku: 'CG-MKP-012',
  },
];

export async function POST() {
  try {
    const count = await db.product.count();

    if (count > 0) {
      return NextResponse.json({ message: 'Products already exist, skipping seed' });
    }

    const products = await Promise.all(
      seedProducts.map((product) =>
        db.product.create({ data: product })
      )
    );

    return NextResponse.json({
      message: `Seeded ${products.length} products successfully`,
      count: products.length,
    });
  } catch (error) {
    console.error('Error seeding products:', error);
    return NextResponse.json({ error: 'Failed to seed products' }, { status: 500 });
  }
}
