import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

// 24 real products from WooCommerce — seed on first deploy or when images are broken
const SEED_PRODUCTS = [
  // ---- MAKEUP (17) ----
  {
    name: 'Fond de Teint Visage et Corps ALL COVER',
    brand: 'ChicGlam by Eva',
    price: 28,
    originalPrice: null,
    image: '/images/products/makeup/fond-de-teint-allcover.png',
    images: '["/images/products/makeup/fond-de-teint-allcover.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.8,
    reviewCount: 124,
    description: "Rendez votre visage rayonnant avec le fond de teint ALL COVER pour visage et corps. Il possède des propriétés antioxydant, anti-bactérien, adoucissant et hydratant. Il unifie le teint, camoufle les imperfections avec sa formule huile contrôlée pour un fini mat et un résultat Zéro défaut. Disponible dans un éventail de 10 teintes.",
    shortDescription: 'Fond de teint visage et corps - 10 teintes - fini mat zéro défaut',
    tags: '["fond-de-teint","couvrant","mat","antioxydant","hydratant","waterproof"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    isActive: true,
    sku: 'CG-FDT-001',
    stockCount: 50,
  },
  {
    name: 'Poudre Compacte HD',
    brand: 'ChicGlam by Eva',
    price: 18,
    originalPrice: null,
    image: '/images/products/makeup/poudre-compacte.png',
    images: '["/images/products/makeup/poudre-compacte.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.7,
    reviewCount: 98,
    description: "Sublimez votre visage avec la poudre compacte en vous offrant un teint uniforme et parfait en HD. 9 nuances disponibles pour tout type de peau de normale à grasse. Vegan, sans cruauté, waterproof, longue tenue.",
    shortDescription: 'Poudre compacte HD - 9 nuances - vegan - waterproof',
    tags: '["poudre-compacte","HD","matifiante","waterproof","vegan","longue-tenue"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PC-002',
    stockCount: 50,
  },
  {
    name: 'Poudre Illuminatrice / Highlighter',
    brand: 'ChicGlam by Eva',
    price: 17,
    originalPrice: null,
    image: '/images/products/makeup/poudre-illuminatrice.png',
    images: '["/images/products/makeup/poudre-illuminatrice.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.6,
    reviewCount: 76,
    description: "Poudre illuminatrice highlighter pour un effet glow naturel. Disponible en 5 teintes pour sublimer tous les tons de peau. Texture légère et fondante pour un résultat lumineux.",
    shortDescription: 'Poudre illuminatrice highlighter - 5 teintes - effet glow',
    tags: '["highlighter","illuminatrice","glow","lumineux"]',
    inStock: true,
    isNew: false,
    isTrending: true,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PI-003',
    stockCount: 40,
  },
  {
    name: 'Poudre Libre / Translucide',
    brand: 'ChicGlam by Eva',
    price: 18,
    originalPrice: null,
    image: '/images/products/makeup/poudre-libre-translucide.png',
    images: '["/images/products/makeup/poudre-libre-translucide.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.5,
    reviewCount: 63,
    description: "Poudre libre translucide avec un effet couvrant tout en laissant la peau paraître naturelle. Parfaite pour tous les teints et disponible en 7 belles nuances. Sa texture soyeuse assure un fini parfait.",
    shortDescription: 'Poudre libre translucide - 7 nuances - fini naturel',
    tags: '["poudre-libre","translucide","naturel","soyeux"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PLT-004',
    stockCount: 40,
  },
  {
    name: 'FLAWLESS FINISH SKIN',
    brand: 'ChicGlam by Eva',
    price: 28,
    originalPrice: 30,
    image: '/images/products/makeup/flawless-finish-skin.jpeg',
    images: '["/images/products/makeup/flawless-finish-skin.jpeg"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.9,
    reviewCount: 87,
    description: "Rendez votre visage rayonnant avec le fond de teint FLAWLESS FINISH SKIN pour visage et corps. Propriétés antioxydant, anti-bactérien, adoucissant et hydratant. Unifie le teint et camoufle les imperfections pour un résultat Zéro défaut.",
    shortDescription: 'Fond de teint Flawless Finish Skin - fini zéro défaut',
    tags: '["fond-de-teint","flawless","antioxydant","hydratant","zéro-défaut"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    isActive: true,
    sku: 'CG-FFS-005',
    stockCount: 40,
  },
  {
    name: 'FLAWLESS FINISH Concealer',
    brand: 'ChicGlam by Eva',
    price: 12,
    originalPrice: null,
    image: '/images/products/makeup/flawless-finish-concealer.jpeg',
    images: '["/images/products/makeup/flawless-finish-concealer.jpeg"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.7,
    reviewCount: 52,
    description: "Notre concealer/correcteur FLAWLESS FINISH riche en pigments est un incontournable du maquillage. Sa formule 95% d'origine naturelle enrichie en actifs hydratants offre une couvrance parfaite et un fini naturel.",
    shortDescription: 'Correcteur Flawless Finish - 95% naturel - couvrance parfaite',
    tags: '["concealer","correcteur","naturel","couvrant","hydratant"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-FFC-006',
    stockCount: 50,
  },
  {
    name: 'Palette Fars à Paupières DIONGUÈ',
    brand: 'ChicGlam by Eva',
    price: 30,
    originalPrice: null,
    image: '/images/products/makeup/palette-diongue.png',
    images: '["/images/products/makeup/palette-diongue.png"]',
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.8,
    reviewCount: 89,
    description: "Palette de 24 fars à paupières avec une variété de couleurs irisées, mats et métalliques très pigmentées pour un fini intense et un wow effet. Waterproof, hypoallergénique, longue tenue, vegan.",
    shortDescription: 'Palette 24 couleurs DIONGUÈ - irisées, mats, métalliques - vegan',
    tags: '["palette","yeux","pigmenté","waterproof","hypoallergénique","vegan"]',
    inStock: true,
    isNew: false,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PD-007',
    stockCount: 30,
  },
  {
    name: 'Palette Fars à Paupières MISS GLAM',
    brand: 'ChicGlam by Eva',
    price: 35,
    originalPrice: null,
    image: '/images/products/makeup/palette-miss-glam.png',
    images: '["/images/products/makeup/palette-miss-glam.png"]',
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.9,
    reviewCount: 112,
    description: "Ajoutez une touche de glamour à votre look avec MISS GLAM. 24 couleurs irisées, mats et métalliques très pigmentées pour un fini intense. Waterproof, hypoallergénique, longue tenue, vegan.",
    shortDescription: 'Palette 24 couleurs MISS GLAM - mats, métalliques - vegan',
    tags: '["palette","yeux","glamour","pigmenté","waterproof","vegan"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    isActive: true,
    sku: 'CG-PMG-008',
    stockCount: 30,
  },
  {
    name: 'Eye-liner Adhésif 2 en 1',
    brand: 'ChicGlam by Eva',
    price: 12,
    originalPrice: null,
    image: '/images/products/makeup/eye-liner-2en1.png',
    images: '["/images/products/makeup/eye-liner-2en1.png"]',
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.6,
    reviewCount: 67,
    description: "Ce stylo eyeliner liquide est doté d'un pinceau à fibre vous permettant de créer un tracé épais, fin ou accentué et colle tout type de faux cils grâce à sa formule 2 en 1. Professionnel, anti-bavure, waterproof, longue tenue.",
    shortDescription: 'Eye-liner 2 en 1 adhésif - eyeliner + colle à cils',
    tags: '["eye-liner","2-en-1","adhésif","waterproof","longue-tenue","anti-bavure"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-EL-009',
    stockCount: 50,
  },
  {
    name: 'Mascara SMUDGE Noir',
    brand: 'ChicGlam by Eva',
    price: 17,
    originalPrice: null,
    image: '/images/products/makeup/mascara-smudge-noir.png',
    images: '["/images/products/makeup/mascara-smudge-noir.png"]',
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.8,
    reviewCount: 93,
    description: "La couleur, le volume, la longueur, en un seul geste. Les cils sont immédiatement magnifiés, allongés, densifiés. Maquille les cils en un seul passage, maxi volume et longueur, séparation parfaite. Tenue 24h, waterproof.",
    shortDescription: 'Mascara SMUDGE noir - volume extrême - tenue 24h',
    tags: '["mascara","volume","longueur","waterproof","tenue-24h","hypoallergénique"]',
    inStock: true,
    isNew: false,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-MS-010',
    stockCount: 50,
  },
  {
    name: 'Mascara Bleu Saphir',
    brand: 'ChicGlam by Eva',
    price: 17,
    originalPrice: null,
    image: '/images/products/makeup/mascara-bleu-saphir.png',
    images: '["/images/products/makeup/mascara-bleu-saphir.png"]',
    category: 'Makeup',
    subcategory: 'Yeux',
    rating: 4.7,
    reviewCount: 41,
    description: "Mascara bleu saphir pour un regard intense et dramatique. Volume, longueur et séparation parfaite des cils. Formule waterproof avec tenue 24h.",
    shortDescription: 'Mascara bleu saphir - regard intense - waterproof',
    tags: '["mascara","bleu-saphir","volume","waterproof","tenue-24h"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-MBS-011',
    stockCount: 40,
  },
  {
    name: 'Crayon à Lèvres, Sourcils et Eyeliner 3 en 1',
    brand: 'ChicGlam by Eva',
    price: 5,
    originalPrice: null,
    image: '/images/products/makeup/crayon-3en1.png',
    images: '["/images/products/makeup/crayon-3en1.png"]',
    category: 'Makeup',
    subcategory: 'Lèvres',
    rating: 4.6,
    reviewCount: 78,
    description: "Ce crayon est 3 en 1 pour vous faciliter votre quotidien : eyeliner, lèvres et sourcils. Sa formule waterproof, lisse et minérale longue tenue dure 24h. Il se fond sur la peau pour une application intense. VEGAN.",
    shortDescription: 'Crayon 3 en 1 lèvres, sourcils, eyeliner - waterproof - vegan',
    tags: '["crayon","3-en-1","lèvres","sourcils","eyeliner","waterproof","vegan"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-C3-012',
    stockCount: 60,
  },
  {
    name: 'Lipstick Chic Kiss',
    brand: 'ChicGlam by Eva',
    price: 15,
    originalPrice: null,
    image: '/images/products/makeup/lipstick-chic-kiss.png',
    images: '["/images/products/makeup/lipstick-chic-kiss.png"]',
    category: 'Makeup',
    subcategory: 'Lèvres',
    rating: 4.8,
    reviewCount: 85,
    description: "Le rouge à lèvres CHIC KISS offre à la fois une excellente hydratation et une bonne tenue grâce à sa formule vegan cruelty free, waterproof. Disponible en 7 teintes vibrantes.",
    shortDescription: 'Rouge à lèvres CHIC KISS - vegan - waterproof - 7 teintes',
    tags: '["lipstick","rouge-à-lèvres","mat","waterproof","vegan","cruelty-free"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    isActive: true,
    sku: 'CG-LCK-013',
    stockCount: 50,
  },
  {
    name: 'Gloss Brillant',
    brand: 'ChicGlam by Eva',
    price: 12,
    originalPrice: null,
    image: '/images/products/makeup/gloss-brillant.jpg',
    images: '["/images/products/makeup/gloss-brillant.jpg"]',
    category: 'Makeup',
    subcategory: 'Lèvres',
    rating: 4.5,
    reviewCount: 34,
    description: "Des nuances vibrantes riches en pigments avec un éclat vibrant qui se mouille et laisse les lèvres avec une finition audacieuse. Peut être porté seul ou par-dessus votre rouge à lèvres préféré.",
    shortDescription: 'Gloss brillant - nuances vibrantes - finition audacieuse',
    tags: '["gloss","brillant","pigmenté","éclat","lèvres"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-GB-014',
    stockCount: 40,
  },
  {
    name: 'Hydratante - Base Fixatrice',
    brand: 'ChicGlam by Eva',
    price: 15,
    originalPrice: null,
    image: '/images/products/makeup/hydratante.png',
    images: '["/images/products/makeup/hydratante.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.7,
    reviewCount: 56,
    description: "Ce primer est une base fixatrice hydratante, un apprêt maquillage qui resserre les pores, matifie et hydrate la peau pour un effet glow. Avec sa couvrance légère, il prépare la peau pour un maquillage longue tenue.",
    shortDescription: 'Base fixatrice hydratante - resserre les pores - effet glow',
    tags: '["primer","hydratante","base","fixateur","pores","glow"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-HYD-015',
    stockCount: 40,
  },
  {
    name: 'Matifiante',
    brand: 'ChicGlam by Eva',
    price: 15,
    originalPrice: null,
    image: '/images/products/makeup/matifiante.png',
    images: '["/images/products/makeup/matifiante.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.6,
    reviewCount: 42,
    description: "Sa formule permet de réduire l'apparence des pores et aide à contrôler l'excès de sébum. Uniformise le teint et atténue les brillances tout en préparant la peau pour un maquillage longue tenue.",
    shortDescription: 'Base matifiante - réduit les pores - contrôle le sébum',
    tags: '["matifiante","pores","sébum","teint-uniforme","longue-tenue"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-MAT-016',
    stockCount: 40,
  },
  {
    name: 'FINISH HD - Spray Fixateur',
    brand: 'ChicGlam by Eva',
    price: 15,
    originalPrice: null,
    image: '/images/products/makeup/finish-hd.png',
    images: '["/images/products/makeup/finish-hd.png"]',
    category: 'Makeup',
    subcategory: 'Teint',
    rating: 4.8,
    reviewCount: 48,
    description: "Découvrez votre nouveau spray nourrissant dans une formule à base de glycérine, sans alcool et sans silicone. Infusé de vitamines, minéraux et d'extraits naturels pour fixer votre maquillage tout en nourrissant la peau.",
    shortDescription: 'Spray fixateur HD - sans alcool - nourrissant',
    tags: '["spray","fixateur","HD","sans-alcool","sans-silicone","nourrissant"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-FHD-017',
    stockCount: 40,
  },
  // ---- ACCESSOIRES (4) ----
  {
    name: 'Cils Magnétiques',
    brand: 'ChicGlam by Eva',
    price: 18,
    originalPrice: null,
    image: '/images/products/accessoires/cils-magnetiques.png',
    images: '["/images/products/accessoires/cils-magnetiques.png"]',
    category: 'Accessoires',
    subcategory: 'Cils',
    rating: 4.7,
    reviewCount: 89,
    description: "Optez pour un regard Chic & Glamour avec nos faux cils magnétiques + eyeliner. 4 volumes naturels disponibles : ultra légers, sans colle, hypoallergénique, facile à utiliser, réutilisable, bonne tenue, waterproof.",
    shortDescription: 'Cils magnétiques - 4 volumes - sans colle - waterproof',
    tags: '["cils-magnétiques","faux-cils","waterproof","réutilisable","hypoallergénique"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-CM-018',
    stockCount: 40,
  },
  {
    name: 'Kit Pinceaux 12 Pièces',
    brand: 'ChicGlam by Eva',
    price: 20,
    originalPrice: null,
    image: '/images/products/accessoires/kit-pinceaux.png',
    images: '["/images/products/accessoires/kit-pinceaux.png"]',
    category: 'Accessoires',
    subcategory: 'Pinceaux',
    rating: 4.8,
    reviewCount: 67,
    description: "Chic & Glamour by Eva vous propose une large sélection d'accessoires. À chaque produit de maquillage son pinceau ! Un kit de 12 superbes pinceaux pour un maquillage professionnel.",
    shortDescription: 'Kit de 12 pinceaux maquillage professionnels',
    tags: '["pinceaux","kit","12-pièces","professionnel"]',
    inStock: true,
    isNew: false,
    isTrending: true,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-KP-019',
    stockCount: 30,
  },
  {
    name: 'Pinceau de Teint Kabuki',
    brand: 'ChicGlam by Eva',
    price: 7,
    originalPrice: null,
    image: '/images/products/accessoires/pinceau-kabuki.png',
    images: '["/images/products/accessoires/pinceau-kabuki.png"]',
    category: 'Accessoires',
    subcategory: 'Pinceaux',
    rating: 4.6,
    reviewCount: 45,
    description: "Pinceau de teint kabuki avec poignée de base à forme de losange aux poils d'une extrême douceur, permettent un maquillage discret, très précis et d'une grande qualité.",
    shortDescription: 'Pinceau kabuki - poils ultra-doux - maquillage précis',
    tags: '["pinceau","kabuki","teint","doux","professionnel"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PK-020',
    stockCount: 40,
  },
  {
    name: 'Perfect Contouring / Concealer Brush',
    brand: 'ChicGlam by Eva',
    price: 6,
    originalPrice: null,
    image: '/images/products/accessoires/perfect-contouring.png',
    images: '["/images/products/accessoires/perfect-contouring.png"]',
    category: 'Accessoires',
    subcategory: 'Pinceaux',
    rating: 4.5,
    reviewCount: 33,
    description: "Cette brosse facilite l'application du correcteur et/ou de l'anticerne. Les poils naturels évitent le gaspillage et permettent d'estomper le produit pour un résultat naturel et professionnel.",
    shortDescription: 'Brosse correcteur/anticerne - poils naturels',
    tags: '["pinceau","concealer","contouring","poils-naturels"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PCB-021',
    stockCount: 40,
  },
  // ---- LINGERIE (3) ----
  {
    name: 'Kit Nuisette',
    brand: 'ChicGlam by Eva',
    price: 65,
    originalPrice: null,
    image: '/images/products/lingerie/kit-nuisette.png',
    images: '["/images/products/lingerie/kit-nuisette.png"]',
    category: 'Lingerie',
    subcategory: 'Nuisettes',
    rating: 4.9,
    reviewCount: 87,
    description: "Instant de grâce charnel et très sensuel avec la collection SECRET DE DAME. Chic & Glamour by Eva a le plaisir de vous offrir un service sur mesure. Kit nuisette élégant fait main avec des matériaux de qualité.",
    shortDescription: 'Kit nuisette SECRET DE DAME - fait main - élégant',
    tags: '["nuisette","kit","séduction","fait-main","secret-de-dame"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: true,
    isFeatured: true,
    isActive: true,
    sku: 'CG-KN-022',
    stockCount: 20,
  },
  {
    name: 'Pagne / Paréo Court',
    brand: 'ChicGlam by Eva',
    price: 15,
    originalPrice: null,
    image: '/images/products/lingerie/pagne-courts.png',
    images: '["/images/products/lingerie/pagne-courts.png"]',
    category: 'Lingerie',
    subcategory: 'Pagnes',
    rating: 4.7,
    reviewCount: 52,
    description: "Ces petits pagnes / paréos sexy courts traditionnels sont l'apanage des Sénégalaises. Ils font office de nuisette ou lingerie et sont les éléments clés de la séduction africaine.",
    shortDescription: 'Pagne court traditionnel - séduction africaine',
    tags: '["pagne","paréo","court","traditionnel","sénégalais","séduction"]',
    inStock: true,
    isNew: true,
    isTrending: true,
    isBestseller: false,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PPC-023',
    stockCount: 30,
  },
  {
    name: 'Pagne / Paréo Long',
    brand: 'ChicGlam by Eva',
    price: 12,
    originalPrice: null,
    image: '/images/products/lingerie/pagne-long.png',
    images: '["/images/products/lingerie/pagne-long.png"]',
    category: 'Lingerie',
    subcategory: 'Pagnes',
    rating: 4.8,
    reviewCount: 41,
    description: "Ces petits pagnes / paréos sexy longs traditionnels sont l'apanage des Sénégalaises. Ils font office de nuisette ou lingerie et sont les éléments clés de la séduction africaine.",
    shortDescription: 'Pagne long traditionnel - séduction africaine',
    tags: '["pagne","paréo","long","traditionnel","sénégalais","séduction"]',
    inStock: true,
    isNew: true,
    isTrending: false,
    isBestseller: true,
    isFeatured: false,
    isActive: true,
    sku: 'CG-PPL-024',
    stockCount: 30,
  },
];

export async function POST() {
  try {
    // Check if we need to seed (DB empty OR has products with broken woocommerce paths)
    const existingCount = await db.product.count();
    
    // Check for products with broken image paths (woocommerce folder no longer exists)
    const brokenProducts = existingCount > 0 
      ? await db.product.count({
          where: {
            OR: [
              { image: { contains: 'woocommerce' } },
              { image: { contains: 'fondation.png' } },
              { image: { contains: 'rouge-a-levres.png' } },
              { image: { contains: 'palette-yeux.png' } },
              { image: { contains: 'nuisette-soie.png' } },
              { image: { contains: 'kimono-africain.png' } },
              { image: { contains: 'ensemble-wax.png' } },
              { image: { contains: 'body-satin.png' } },
              { image: { contains: 'cils-faux.png' } },
              { image: { contains: 'pinceaux-set.png' } },
              { image: { contains: 'tour-de-taille.png' } },
              { image: { contains: 'box-de-seduction/' } },
            ],
          },
        })
      : 0;

    if (existingCount === SEED_PRODUCTS.length && brokenProducts === 0) {
      return NextResponse.json({
        success: true,
        message: `Products already seeded correctly (${existingCount} found). Skipping.`,
        count: existingCount,
      });
    }

    // Clear ALL existing products (including broken ones)
    if (existingCount > 0) {
      await db.product.deleteMany({});
    }

    // Create all 24 products
    const productsToCreate = SEED_PRODUCTS.map((p) => ({
      ...p,
      slug: p.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, ''),
    }));

    const result = await db.product.createMany({
      data: productsToCreate,
    });

    return NextResponse.json({
      success: true,
      message: brokenProducts > 0
        ? `Cleared ${existingCount} old products (including ${brokenProducts} with broken paths) and seeded ${result.count} new products.`
        : `Seeded ${result.count} products successfully.`,
      count: result.count,
      cleared: existingCount,
      brokenFixed: brokenProducts,
    });
  } catch (error) {
    console.error('Product seed error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to seed products' },
      { status: 500 }
    );
  }
}
